language: python
os: linux
python:
  - "2.7"
  - "3.8"
services:
  - mysql
env:
  - DB=django.db.backends.sqlite3 DATABASE_NAME=mawareeth MONGOLAB_URI=None
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
before_script:
  - sudo python3 manage.py makemigrations
  - sudo python3 manage.py migrate
script:
  - python manage.py test
