language: python
    python:
      - "3.8"
    services:
      - mysql
    env:
      -DJANGO=2.2 DB=sqlite3
    install:
      - pip install -r requirements.txt
    script:
      - python manage.py test
