language: python
os: linux
python:
  - "3.8"
services:
  - mongodb
env:
  -  DB=mongodb ENGINE=djongo DATABASE_NAME=mydb_test MONGOLAB_URI=localhost
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["userAdminAnyDatabase", "dbAdminAnyDatabase", "readWriteAnyDatabase"]});'
  - python3 manage.py makemigrations
  - python3 manage.py migrate
script:
  - python manage.py test
