language: python
os: linux
python:
  - "3.8"
services:
  - mysql
env:
  -DJANGO=2.2 DB=sqlite3 DATABASE_NAME=mawareeth MONGOLAB_URI=None
install:
  - pip install -r requirements.txt

script:
  - python manage.py test
