language: python
os: linux
python:
  - "3.8"
services:
  - sqlite3
env:
  -  DB=sqlite ENGINE=django.db.backends.sqlite3 DATABASE_NAME=mawareeth MONGOLAB_URI=localhost
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
script:
  - python manage.py test
