language: python
os: linux
python:
  - "3.8"
services:
  - postgresql
env:
  -  DB=postgres ENGINE=django.db.backends.postgresql_psycopg2 DATABASE_NAME=mydb_test DATABASE_HOST=localhost DJANGO_KEY=")vzug)78j&h83(=h^&=@n%b(()ai!dryu!88++oij_)gl9oa1_" DEBUG=False

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database mydb_test;' -U postgres
  - python3 manage.py waffle_switch Result off --create
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - python manage.py collectstatic
script:
  - python3 manage.py test
