language: python
python:
  - "3.8"
services:
  - mysql
env:
  -DJANGO=2.2 DB=mysql DATABASE_NAME=mawareeth
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database test;' -u root
script:
  - python manage.py test
