language: python
os: linux
python:
  - "3.8"
services:
  - mysql
env:
  - DB=django.db.backends.sqlite3 DATABASE_NAME=mawareeth MONGOLAB_URI=None
install:
  - source ~/virtualenv/python3.8/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python -m pip install django==2.2
before_script:
  - sudo python3 manage.py makemigrations
  - sudo python3 manage.py migrate
script:
  - python manage.py test
