language: python
os: linux
python:
  - "3.8"
services:
  - mysql
env:
  -DJANGO=2.2 DB=django.db.backends.sqlite3 DATABASE_NAME=mawareeth MONGOLAB_URI=None
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations -u root
  - python manage.py migrate -u root
script:
  - python manage.py test
