name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DB: postgres 
  ENGINE: django.db.backends.postgresql_psycopg2 
  DATABASE_NAME: mydb_test 
  DATABASE_HOST: localhost 
  DJANGO_KEY: ")vzug)78j&h83(=h^&=@n%b(()ai!dryu!88++oij_)gl9oa1_" 
  DEBUG: False
  MAILGUN_ACCESS_KEY: ${{ secrets.MAILGUN_ACCESS_KEY }}
  MAILGUN_SERVER_NAME: ${{ secrets.MAILGUN_SERVER_NAME }}
  DB_USER: postgres
  DB_PASS: postgres

jobs:
  build:
    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up
      run: |
        psql -c 'create database mydb_test;'
        python3 manage.py makemigrations
        python3 manage.py migrate
        python manage.py collectstatic

    - name: Run Tests
      run: |
        python manage.py test
